# influxclean sample config
[[influxdb1]]
  url = "http://localhost:8086"
  env_user = "INFLUX_USER"
  env_password = "INFLUX_PWD"
  ## Use TLS but skip chain & host verification (default false)
  insecure_skip_verify = false
  # drop series from all measurements for Windows servers
  # with no win_system data in telegraf db for three days (72h)
  [[influxdb1.oldseries]]
    name = "Windows servers"
    # if databases is empty all databases are checked
    databases = ["telegraf"]
    # retention policy, measurement and field to use in queries
    rp = "autogen"
    measurement = "win_system"
    field = "Processor_Queue_Length"
    # tags to detect old series (no more than two)
    tags = ["host"]
    # if drop_from_all is true series are dropped from all
    # measurements, otherwise (default) only from measurement
    drop_from_all = true
    # sleep duration time before jumping to the next database
    sleep_duration = "0s"
    # time windows (relative to now) to query for data in db
    # "0m", "0m" performs a search without time restriction
    history_window = ["0m", "0m"]
    current_window = ["72h", "1m"]
